1 version: '3.8'
2 services:
   telegram-bot:
     build:.
     environment:
       - BOT_TOKEN=8701172834:AAHiFRflATS1Z8uKv-a7EBL9dx4eFhhI65M
       - API_URL_TEMPLATE=https://no-permanent-like-api.vercel.app/like?uid={uid}&server_name={region}
       - WEBHOOK_URL=$https://no-permanent-like-bot-uooc.onrender.com
        - PORT=$5000
     ports:
        - "$5000:$5000"
     restart: unless-stopped
     deploy:
       resources:
         limits:
          cpus: '0.5'
          memory: 512M
